### ISSUE TITLE
Crackme09 solution is incorrect

### ISSUE THREAD

**Issue by Leopounet** [LeoTindall/crackmes#16]
I know I am reviving an old github repo, but still it may be useful to someone else.

Crackme n°9 states that:

```c
// Require that the input string pass a state machine matching:
// Qz+327x*n+[l9]+
``` 

This is almost true except it should be:

```c
// Require that the input string pass a state machine matching:
// Qz+327x*n{2,}[l9]+
``` 

The difference being that there should be at least two 'n' characters.

**Comment by NoraCodes** [comment]
Thanks for reporting this! It's an old repo, but only because I have no real reason to edit this stuff. Mistakes are a good reason!

Looking into this, I actually found some other errors in this regex. I thiiiink this is the correct one: `Qz+327x*[^n]n+(l9)+`

Test cases:

Qz327xnl (bad)
Qz327xn9 (bad)
Qz327xnnl (bad)
Qz327xnn9 (bad)
Qzzz327xnnnl (bad)
Qzzz327xnnn9 (bad)
Qzzz327nnnl (bad)
Qzzz327nnn9 (bad)
Qz327xkn9l (bad)
Qz327xknl9 (good)
Qz327xxxknl9 (good)
Qz327knl9 (good)
